# Generated by Django 3.1.4 on 2021-01-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_checkoutaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutaddress',
            old_name='zip',
            new_name='pin',
        ),
    ]
